export { galleryService, type GalleryImage } from './gallery.service';
export { productService, type Product } from './product.service';
export { categoryService, type Category, type Subcategory } from './category.service';
export { collectionService, type Collection } from './collection.service';
export { uploadService } from './upload.service';
export { filterService, type FilterOption, type FilterOptionsByGroup } from './filter.service';
export { projectService, type Project } from './project.service';
export { processService, type ProcessStep } from './process.service';
export { testimonialService, type Testimonial } from './testimonial.service';
export { heroService, type DecorHeroData, type InteriorHeroData } from './hero.service';
export { featuresService, type DecorFeaturesData, type QuickFeature, type Badge } from './features.service';
export { interiorService, type InteriorCategory, type InteriorProject } from './interior.service';
export { legacyProjectService, type LegacyProject, type LegacySettings } from './legacy-project.service';
export { interiorServicesService, type InteriorService } from './services.service';
export { inquiryService, type Inquiry } from './inquiry.service';
export { orderService, type Order, type OrderItem } from './order.service';
export { calculatorService, type CalculatorItem, type BrandOption, type CalculatorData } from './calculator.service';
